<?php

/* NOTE: DO NOT CHANGE THIS FILE. IF YOU WANT TO UPDATE THE LANGUAGE THEN COPY THIS FILE TO custom_lang.php AND UPDATE THERE */

$lang["twofactor"] = "Two-factor";
$lang["twofactor_settings"] = "Two-factor settings";
$lang["twofactor_email_subject"] = "Email subject";
$lang["twofactor_email_message"] = "Email message";
$lang["twofactor_twofactor_authentication"] = "Two-factor authentication";
$lang["twofactor_enable_twofactor_authentication"] = "Enable two-factor authentication";
$lang["twofactor_info_text"] = "Before you logout, please open a new browser and make sure the Two-factor authentication is working.";
$lang["twofactor_code"] = "Code";
$lang["twofactor_code_expaired_message"] = "The two-factor code has expired or something went wrong.";
$lang["twofactor_code_message"] = "An OTP has been sent to your email. Please grab that to continue.";
$lang["twofactor_code_success_message"] = "Logged in successfully. Redirecting to the dashboard...";
$lang["twofactor_continue"] = "Continue";
$lang["twofactor_not_you"] = "Not you?";
$lang["twofactor_restore_email_message_to_default"] = "Restore email message to default";
$lang["twofactor_email_message_restored"] = "The email message has been restored to default!";

/* Version: 1.1 */

$lang["twofactor_method"] = "Method";
$lang["twofactor_send_otp"] = "Send OTP";
$lang["twofactor_qr_code"] = "QR Code";
$lang["twofactor_google_authenticator_help_message"] = "Scan this QR Code with your Google Authenticator app and enter the verification code below.";

$lang["twofactor_enable_sms"] = "Enable SMS";
$lang["twofactor_twilio_account_sid"] = "Account SID";
$lang["twofactor_twilio_auth_token"] = "Auth Token";
$lang["twofactor_twilio_phone_number"] = "Twilio Phone Number";
$lang["twofactor_send_test_sms"] = "Send test SMS";

$lang["twofactor_twilio_phone_no_help_message"] = "Phone numbers must be in format %s. Otherwise he/she won't get SMS.";
$lang["twofactor_twilio_user_phone_no_help_message"] = "Please use %s format (<b>+14155552671</b>) in user/client phone number. Otherwise the SMS OTP won't work. Click %s to read more how phone numbers should be formatted.";

$lang["twofactor_send_test_sms_successfull_message"] = "Test SMS has been sent successfully!";
$lang["twofactor_send_test_sms_error_message"] = "Error! Can't connect with the Twilio using the credentials.";

$lang["twofactor_here"] = "Here";
$lang["twofactor_restore_template_to_default"] = "Restore template to default";

$lang["twofactor_code_message_email"] = "An OTP has been sent to your email. Please grab that to continue.";
$lang["twofactor_code_message_sms"] = "An OTP has been sent to your phone. Please grab that to continue.";
$lang["twofactor_code_message_google_authenticator"] = "Please enter the 6-digit verification code generated by your authenticator app.";

$lang["twofactor_enable_email_authentication_for_all"] = "Enable email authentication for all";
$lang["twofactor_enable_email_authentication_for_all_help_message"] = "If you enable email authentication for all, it'll only be applied to users who doesn't have any two-factor authentication enabled from their personal profile.";

return $lang;
